services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raiders_app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      - db
    networks:
      - red_db

  db:
    image: mysql:8.0
    container_name: raiders_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: raidersparadise
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: raiders_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8881:80"
    depends_on:
      - db
    networks:
      - red_db

networks:
  red_db:

volumes:
  mysql_data:
  vendor: